services:
  db:
    hostname: bcms-db
    image: mongo:6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test1234
    volumes:
      - type: bind
        source: ./backend/db/mongo
        target: /data/db
    logging:
      driver: none
  backend:
    hostname: 'bcms-backend'
    depends_on:
      - db
    build:
      context: './backend'
      dockerfile: dev.Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - type: bind
        source: ./backend/bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./backend/src
        target: /app/src
      - type: bind
        source: ./backend/db
        target: /app/db
      - type: bind
        source: ./backend/uploads
        target: /app/uploads
  ui:
    hostname: 'bcms-ui'
    build:
      context: './ui'
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./ui/public
        target: /app/public
      - type: bind
        source: ./ui/src
        target: /app/src
      - type: bind
        source: ./ui/tailwind.config.cjs
        target: /app/tailwind.config.cjs
      - type: bind
        source: ./ui/postcss.config.cjs
        target: /app/postcss.config.cjs
      - type: bind
        source: ./ui/vite.config.ts
        target: /app/vite.config.ts
      - type: bind
        source: ./ui/sdk/src
        target: /app/sdk/src
  proxy:
    hostname: 'bcms-proxy'
    depends_on:
      - backend
      - ui
      - db
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    # logging:
    #   driver: none
