version: '3.9'
services:
  cms_proxy:
    build: 'proxy/.'
    ports:
      - '8080:8080'
    logging:
      driver: none
  cms_shim:
    container_name: bcms-shim
    hostname: bcms-shim
    depends_on:
      - cms_proxy
    image: 'becomes/cms-shim-local:1.0.5'
    ports:
      - '1279:1279'
    logging:
      driver: none
  cms_backend:
    depends_on:
      - cms_shim
    image: 'becomes/cms-backend-local:1.1.2'
    ports:
      - '1280:8080'
    volumes:
      - type: bind
        source: ./bcms.config.js
        target: /app/bcms.config.js
      - type: bind
        source: ./package.json
        target: /app/custom-package.json
      - type: bind
        source: ./shim.json
        target: /app/shim.json
      - type: bind
        source: ./db
        target: /app/db
      - type: bind
        source: ./uploads
        target: /app/uploads
      - type: bind
        source: ./src/functions
        target: /app/functions
      - type: bind
        source: ./src/events
        target: /app/events
      - type: bind
        source: ./src/jobs
        target: /app/jobs
      - type: bind
        source: ./src/additional
        target: /app/additional
      - type: bind
        source: ./plugins
        target: /app/plugins
