openapi: 3.0.0
info:
  version: 2.0.0
  title: Becomes CMS - REST API
  description: This is Swagger documentation for REST API of BCMS. It is recommended to use
    provided tools (like @becomes/cms-client) for communication with CMS but if you need
    to implement some custom solution this documentation will help you. You can also
    see our GraphQL API.
  contact:
    name: Becomes
    url: https://becomes.co/cms
    email: office@becomes.co

servers:
  - url: http://localhost:@PORT/api
    description: Local server.

paths:
  /test:
    get:
      tags:
        - Test
      responses:
        "200":
          description: OK

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    AccessToken:
      type: http
      scheme: bearer
    RefreshToken:
      type: http
      scheme: bearer
